### ISSUE TITLE
Thumbnail Images With Nonexistent Sources Are Incorrectly Sized

### ISSUE THREAD

**Issue by adamhb123** [ComputerScienceHouse/gallery#80]
If a thumbnail's image source is unavailable, the element's height is far smaller than the others, throwing off grid sizing and element positioning.

I have a pure-CSS solution to this that may or may not be satisfactory, and will submit a PR soon.

Example: ![Visual example of issue](https://user-images.githubusercontent.com/25161597/128654874-33bf5418-6106-4b12-88a9-eb68cee53f41.png)

**Comment by jabbate19** [comment]
It appears what is happening is Gallery is making a call to S3 for the photo, and S3 is giving a 404 (likely deleted photo). The request needs to be checked beforehand and if it gets a 404, call the refresh
