### ISSUE TITLE
Create Functionality for Organizer Role

### ISSUE THREAD

**Issue by mbreidenbach** [ComputerScienceHouse/gallery#82]
We're considering the creation of a Gallery Maintainer role. It's unsure how exactly this role will function, but after some discussion with both eboard and RTPs, we are leaning towards letting the maintainer have some admin privilege's on gallery, but not all of them. This will require some work on the gallery-side of things.

This new "Organizer" should have these qualities:
- Can move others files around
- Cannot delete others files
- Cannot view hidden files

See https://discourse.csh.rit.edu/t/opcomm-notes-09-september-2021/130305 for some more information.

**Comment by sauriol** [comment]
The `can_edit` group (eboard + rtp + author, see `render_dir` and `render_file` in `gallery/__init__.py`) currently gates both the move _and_ delete buttons in the `view_dir` and `view_file` templates.
